classdef binlabelpb
    % The abstract base class to represent a binary labeling problem
    %
    
    % Created by Dahua Lin, on April 21, 2010
    %
    
    methods
        q = infer_q(obj, L1, L0)
        % Infer the probabilities of labels given the likelihoods
        %
        %   q = obj.infer_q(L1, L0);
        %       infer the probabilities of labels given the likelihoods.
        %       Here, L1 and L0 are respectively row vectors of likelihood
        %       values. In particular, L1(i) and L0(i) are the likelihood
        %       of the i-th sample, respectively conditioned on that
        %       it is generated by the model corresponding to the label 1
        %       and that corresponding to the label 0.
        %
        %       q can be a row vector of size 1 x n, with q(i) giving 
        %       the marginal probability that the i-th sample is generated
        %       from the model corresponding to the label 1.
        %
        
        v = eval_qscore(obj, q)
        % Evaluates the score of the labeling given by q
        %
        %   v = obj.eval_qscore(q);
        %       Evaluates the score of labeling given by q. The score
        %       depends on the particular labeling model. Generally,
        %       a greater score indicates that q is more consistent
        %       with the prior labeling model.
        %
                
    end
    
end